"""added Link data tables migration.

Revision ID: 82e6e36ffb24
Revises: 
Create Date: 2023-06-29 23:31:08.694199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e6e36ffb24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('short_link', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('custom_path', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['short_link'])
        batch_op.create_unique_constraint(None, ['custom_path'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('short_url')
        batch_op.drop_column('views')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('views', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('short_url', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('clicks')
        batch_op.drop_column('custom_path')
        batch_op.drop_column('short_link')
        batch_op.drop_column('long_link')

    # ### end Alembic commands ###
